### PR TITLE
BITMAKER-1830 Update command line Estela CLI to support DataRetention fields

### PR DESCRIPTION
**Pull request by raymond1242**

### CODE REVIEW

**Comment by raymond1242** [comment]
@mgonnav

**Review by mgonnav — APPROVED** [review]
Looks good! I've made a few fixes and I think it's ready to be merged :)

**Review by mgonnav — APPROVED** [review]
Looks good! I've made a few fixes and I think it's ready to be merged :)

**Comment by raymond1242** [comment]
@mgonnav from Ticket : https://tasks.bitmaker.dev/issues/1830

**Pull request merged**
